### ISSUE TITLE
How do the format functionality work?

### ISSUE THREAD

**Issue by kiikoh** [exension/hwinfo-streamdeck#2]

**Comment by exension** [comment]
The format functionality is string formatting, pulled from Go (the programming language the plugin is written in), but is common in generally every programming language or even programs like Excel.

In short, "%f" specifies a floating-point number (think number with a decimal point, like 123.45).
You can specify the desired precision by adding format rules.

Assume the value of `123.45`

* `%f` outputs `123.45`, standard formatting
* `%.1f` specifies precision of 1 (one-decimal-place) and outputs `123.5` (rounded)
* %.0f` omits decimal places and outputs: `123`

This is just the basics, but if you want to learn more take a look at the following links. Note, the plugin uses floating-point numbers for all values, so everything is based on the basic "%f".

Here's a site showing examples:
https://gobyexample.com/string-formatting

Here's the documentation:
https://golang.org/pkg/fmt/#hdr-Printing
