### ISSUE TITLE
Support line breaks in titles

### ISSUE THREAD

**Issue by Jaxel** [exension/hwinfo-streamdeck#4]
Could line break support be added for tile icons?

**Comment by exension** [comment]
Completely reasonable request.

The easiest thing to do would be to revert to Stream Deck's default Title rendering. When I first wrote the plugin it wasn't as smooth looking, the font wasn't as good and it was off-center enough to really bother me.

I replaced the default title rendering with custom text rendering. It's low-level text rendering and currently supports single line. If the default text renderer still looks wonky (which I'm guessing it does). 

Then I can see adding support for this. It's a little more complicated than you think but I have a shortcut in mind that could make it work.

**Comment by exension** [comment]
Alright went ahead and went with the idea I had that minimized changes. It worked. Check out v1.1.1

**Comment by Jaxel** [comment]
Great! However, now the readings are too close to the title. Could we move the reading down one line, if we use line break titles?
