### ISSUE TITLE
Not working on AMD

### ISSUE THREAD

**Issue by Stefan-Z-Camilleri** [exension/hwinfo-streamdeck#5]
I love the idea of the extension (I'm on v1.1.1)

Sadly it does not work on my machine... no matter what I do, I'm always presented with 'Please Launch HWiNFO64'.

CPU: AMD Threadripper 2990WX

HWiNFO is running (v6.08-3830) and set up as described in the README.md

I also tried running stream deck software with elevated privileges, to no avail.

*Note*: The list of sensors loads just fine, meaning that there is 'some' form of communication going on with HWiNFO64.

![image](https://user-images.githubusercontent.com/20099218/60090529-0391ca80-9743-11e9-81d0-702aca36e1ef.png)

Followed by:
![image](https://user-images.githubusercontent.com/20099218/60090577-17d5c780-9743-11e9-9113-b21d3f7b807b.png)

**Comment by 123swk123** [comment]
Me too facing the same issue, do you have any requirement on HWinfo application version? I am using the latest one 6.08-3830

**Comment by Stefan-Z-Camilleri** [comment]
**Update**: I tried the _installer_ version of HWiNFO v6.08-3830 and it works just fine.  I was using the portable version before.

CC: @123swk123

**Comment by 123swk123** [comment]
I did doubt that portable version or administrator mode might be the root cause. by the way rainmeter works fine with portable version.

**Comment by djbill** [comment]
> 
> 
> **Update**: I tried the _installer_ version of HWiNFO v6.08-3830 and it works just fine. I was using the portable version before.
> 
> CC: @123swk123

I have the same issue with I7-8700k, after installing the "Intaller Version" of HWiNFO all works fine.

**Comment by shayne** [comment]
Good to know. I have an 8700k fwiw. Link to versions that aren't working?

**Comment by shayne** [comment]
I'll try portable and see what's up. Not sure why it'd be different off the top of my head.

**Comment by exension** [comment]
Will look into portable version. For now I'll update README to recommend the Installer Version
