### ISSUE TITLE
Doesn't Currently Read Sensor Data

### ISSUE THREAD

**Issue by igloo15** [exension/hwinfo-streamdeck#7]
Current build with Stream Deck 4.3.1, plugin 1.1.1 and HWiNFO 6.0.8 Portable does not work. 

I have my settings setup exactly like in the guide. I have restarted HWiNFO multiple times and the display still does not work. Surprisingly it does see the sensors because it allows me to select a sensor and reading. Upon selection of a reading though it immediate goes to the plugin error screen and says its unable to communicate with HWiNFO. So it is at least partially communicating with HWiNFO or else it wouldn't be able to figure out what my sensors and readings are.

**Comment by exension** [comment]
Did you take a look at #5. Portable is known not to work right now. If you use the installer version you should find success.
